[package]
name = "reflection-tui"
version = "0.1.0"
edition = "2018"

[dependencies]
crossterm = "0.21.0"

tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
serde = { version = "1.0.129", features = ["derive"] }

reflection = { path = "../reflection" }
