[package]
name = "rusb-test"
version = "0.1.0"
edition = "2018"

[dependencies]
rusb = "0.9.0"
crossterm = "0.21.0"

tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }

antigen-hid = { path = "../antigen-hid" }
