/// Describes the usage of a report descriptor main item with respect to its usage table
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum Usage {
    GenericDesktop(GenericDesktopUsage),
    Other(u32),
}

impl std::fmt::Debug for Usage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Usage::GenericDesktop(usage) => {
                f.write_fmt(format_args!("GenericDesktop::{:?}", usage))
            }
            Usage::Other(usage) => f.write_fmt(format_args!("Other({:?})", usage)),
        }
    }
}

impl std::fmt::Display for Usage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Usage::GenericDesktop(usage) => {
                f.write_fmt(format_args!("{}", usage))
            }
            Usage::Other(usage) => f.write_fmt(format_args!("{}", usage)),
        }
    }
}

/// Describes general-purpose PC input devices and their outputs
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum GenericDesktopUsage {
    Undefined,
    Pointer,
    Mouse,
    Reserved(u32),
    Joystick,
    GamePad,
    Keyboard,
    Keypad,
    MultiAxisController,
    TabletPcSystemControls,
    X,
    Y,
    Z,
    Rx,
    Ry,
    Rz,
    Slider,
    Dial,
    Wheel,
    HatSwitch,
    CountedBuffer,
    ByteCount,
    MotionWakeup,
    Start,
    Select,
    Vx,
    Vy,
    Vz,
    Vbrx,
    Vbry,
    Vbrz,
    Vno,
    FeatureNotification,
    ResolutionMultiplier,
    SystemControl,
    SystemPowerDown,
    SystemSleep,
    SystemWakeUp,
    SystemContextMenu,
    SystemMainMenu,
    SystemAppMenu,
    SystemMenuHelp,
    SystemMenuExit,
    SystemMenuSelect,
    SystemMenuRight,
    SystemMenuLeft,
    SystemMenuUp,
    SystemMenuDown,
    SystemColdRestart,
    SystemWarmRestart,
    DpadUp,
    DpadDown,
    DpadRight,
    DpadLeft,
    SystemDock,
    SystemUndock,
    SystemSetup,
    SystemBreak,
    SystemDebuggerBreak,
    ApplicationBreak,
    ApplicationDebuggerBreak,
    SystemSpeakerMute,
    SystemHibernate,
    SystemDisplayInvert,
    SystemDisplayInternal,
    SystemDisplayExternal,
    SystemDisplayBoth,
    SystemDisplayDual,
    SystemDisplayToggleIntExt,
    SystemDisplaySwapPrimarySecondary,
    SystemDisplayLcdAutoscale,
}

impl std::fmt::Display for GenericDesktopUsage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            GenericDesktopUsage::Undefined => "Undefined",
            GenericDesktopUsage::Pointer => "Pointer",
            GenericDesktopUsage::Mouse => "Mouse",
            GenericDesktopUsage::Reserved(_) => "Reserved(_)",
            GenericDesktopUsage::Joystick => "Joystick",
            GenericDesktopUsage::GamePad => "GamePad",
            GenericDesktopUsage::Keyboard => "Keyboard",
            GenericDesktopUsage::Keypad => "Keypad",
            GenericDesktopUsage::MultiAxisController => "MultiAxisController",
            GenericDesktopUsage::TabletPcSystemControls => "TabletPcSystemControls",
            GenericDesktopUsage::X => "X",
            GenericDesktopUsage::Y => "Y",
            GenericDesktopUsage::Z => "Z",
            GenericDesktopUsage::Rx => "Rx",
            GenericDesktopUsage::Ry => "Ry",
            GenericDesktopUsage::Rz => "Rz",
            GenericDesktopUsage::Slider => "Slider",
            GenericDesktopUsage::Dial => "Dial",
            GenericDesktopUsage::Wheel => "Wheel",
            GenericDesktopUsage::HatSwitch => "HatSwitch",
            GenericDesktopUsage::CountedBuffer => "CountedBuffer",
            GenericDesktopUsage::ByteCount => "ByteCount",
            GenericDesktopUsage::MotionWakeup => "MotionWakeup",
            GenericDesktopUsage::Start => "Start",
            GenericDesktopUsage::Select => "Select",
            GenericDesktopUsage::Vx => "Vx",
            GenericDesktopUsage::Vy => "Vy",
            GenericDesktopUsage::Vz => "Vz",
            GenericDesktopUsage::Vbrx => "Vbrx",
            GenericDesktopUsage::Vbry => "Vbry",
            GenericDesktopUsage::Vbrz => "Vbrz",
            GenericDesktopUsage::Vno => "Vno",
            GenericDesktopUsage::FeatureNotification => "FeatureNotification",
            GenericDesktopUsage::ResolutionMultiplier => "ResolutionMultiplier",
            GenericDesktopUsage::SystemControl => "SystemControl",
            GenericDesktopUsage::SystemPowerDown => "SystemPowerDown",
            GenericDesktopUsage::SystemSleep => "SystemSleep",
            GenericDesktopUsage::SystemWakeUp => "SystemWakeUp",
            GenericDesktopUsage::SystemContextMenu => "SystemContextMenu",
            GenericDesktopUsage::SystemMainMenu => "SystemMainMenu",
            GenericDesktopUsage::SystemAppMenu => "SystemAppMenu",
            GenericDesktopUsage::SystemMenuHelp => "SystemMenuHelp",
            GenericDesktopUsage::SystemMenuExit => "SystemMenuExit",
            GenericDesktopUsage::SystemMenuSelect => "SystemMenuSelect",
            GenericDesktopUsage::SystemMenuRight => "SystemMenuRight",
            GenericDesktopUsage::SystemMenuLeft => "SystemMenuLeft",
            GenericDesktopUsage::SystemMenuUp => "SystemMenuUp",
            GenericDesktopUsage::SystemMenuDown => "SystemMenuDown",
            GenericDesktopUsage::SystemColdRestart => "SystemColdRestart",
            GenericDesktopUsage::SystemWarmRestart => "SystemWarmRestart",
            GenericDesktopUsage::DpadUp => "DpadUp",
            GenericDesktopUsage::DpadDown => "DpadDown",
            GenericDesktopUsage::DpadRight => "DpadRight",
            GenericDesktopUsage::DpadLeft => "DpadLeft",
            GenericDesktopUsage::SystemDock => "SystemDock",
            GenericDesktopUsage::SystemUndock => "SystemUndock",
            GenericDesktopUsage::SystemSetup => "SystemSetup",
            GenericDesktopUsage::SystemBreak => "SystemBreak",
            GenericDesktopUsage::SystemDebuggerBreak => "SystemDebuggerBreak",
            GenericDesktopUsage::ApplicationBreak => "ApplicationBreak",
            GenericDesktopUsage::ApplicationDebuggerBreak => "ApplicationDebuggerBreak",
            GenericDesktopUsage::SystemSpeakerMute => "SystemSpeakerMute",
            GenericDesktopUsage::SystemHibernate => "SystemHibernate",
            GenericDesktopUsage::SystemDisplayInvert => "SystemDisplayInvert",
            GenericDesktopUsage::SystemDisplayInternal => "SystemDisplayInternal",
            GenericDesktopUsage::SystemDisplayExternal => "SystemDisplayExternal",
            GenericDesktopUsage::SystemDisplayBoth => "SystemDisplayBoth",
            GenericDesktopUsage::SystemDisplayDual => "SystemDisplayDual",
            GenericDesktopUsage::SystemDisplayToggleIntExt => "SystemDisplayToggleIntExt",
            GenericDesktopUsage::SystemDisplaySwapPrimarySecondary => {
                "SystemDisplaySwapPrimarySecondary"
            }
            GenericDesktopUsage::SystemDisplayLcdAutoscale => "SystemDisplayLcdAutoscale",
        })
    }
}

impl From<u32> for GenericDesktopUsage {
    fn from(v: u32) -> Self {
        match v {
            0x00 => GenericDesktopUsage::Undefined,
            0x01 => GenericDesktopUsage::Pointer,
            0x02 => GenericDesktopUsage::Mouse,
            0x04 => GenericDesktopUsage::Joystick,
            0x05 => GenericDesktopUsage::GamePad,
            0x06 => GenericDesktopUsage::Keyboard,
            0x07 => GenericDesktopUsage::Keypad,
            0x08 => GenericDesktopUsage::MultiAxisController,
            0x09 => GenericDesktopUsage::TabletPcSystemControls,
            0x30 => GenericDesktopUsage::X,
            0x31 => GenericDesktopUsage::Y,
            0x32 => GenericDesktopUsage::Z,
            0x33 => GenericDesktopUsage::Rx,
            0x34 => GenericDesktopUsage::Ry,
            0x35 => GenericDesktopUsage::Rz,
            0x36 => GenericDesktopUsage::Slider,
            0x37 => GenericDesktopUsage::Dial,
            0x38 => GenericDesktopUsage::Wheel,
            0x39 => GenericDesktopUsage::HatSwitch,
            0x3A => GenericDesktopUsage::CountedBuffer,
            0x3B => GenericDesktopUsage::ByteCount,
            0x3C => GenericDesktopUsage::MotionWakeup,
            0x3D => GenericDesktopUsage::Start,
            0x3E => GenericDesktopUsage::Select,
            0x40 => GenericDesktopUsage::Vx,
            0x41 => GenericDesktopUsage::Vy,
            0x42 => GenericDesktopUsage::Vz,
            0x43 => GenericDesktopUsage::Vbrx,
            0x44 => GenericDesktopUsage::Vbry,
            0x45 => GenericDesktopUsage::Vbrz,
            0x46 => GenericDesktopUsage::Vno,
            0x47 => GenericDesktopUsage::FeatureNotification,
            0x48 => GenericDesktopUsage::ResolutionMultiplier,
            0x80 => GenericDesktopUsage::SystemControl,
            0x81 => GenericDesktopUsage::SystemPowerDown,
            0x82 => GenericDesktopUsage::SystemSleep,
            0x83 => GenericDesktopUsage::SystemWakeUp,
            0x84 => GenericDesktopUsage::SystemContextMenu,
            0x85 => GenericDesktopUsage::SystemMainMenu,
            0x86 => GenericDesktopUsage::SystemAppMenu,
            0x87 => GenericDesktopUsage::SystemMenuHelp,
            0x88 => GenericDesktopUsage::SystemMenuExit,
            0x89 => GenericDesktopUsage::SystemMenuSelect,
            0x8A => GenericDesktopUsage::SystemMenuRight,
            0x8B => GenericDesktopUsage::SystemMenuLeft,
            0x8C => GenericDesktopUsage::SystemMenuUp,
            0x8D => GenericDesktopUsage::SystemMenuDown,
            0x8E => GenericDesktopUsage::SystemColdRestart,
            0x8F => GenericDesktopUsage::SystemWarmRestart,
            0x90 => GenericDesktopUsage::DpadUp,
            0x91 => GenericDesktopUsage::DpadDown,
            0x92 => GenericDesktopUsage::DpadRight,
            0x93 => GenericDesktopUsage::DpadLeft,
            0xA0 => GenericDesktopUsage::SystemDock,
            0xA1 => GenericDesktopUsage::SystemUndock,
            0xA2 => GenericDesktopUsage::SystemSetup,
            0xA3 => GenericDesktopUsage::SystemBreak,
            0xA4 => GenericDesktopUsage::SystemDebuggerBreak,
            0xA5 => GenericDesktopUsage::ApplicationBreak,
            0xA6 => GenericDesktopUsage::ApplicationDebuggerBreak,
            0xA7 => GenericDesktopUsage::SystemSpeakerMute,
            0xA8 => GenericDesktopUsage::SystemHibernate,
            0xB0 => GenericDesktopUsage::SystemDisplayInvert,
            0xB1 => GenericDesktopUsage::SystemDisplayInternal,
            0xB2 => GenericDesktopUsage::SystemDisplayExternal,
            0xB3 => GenericDesktopUsage::SystemDisplayBoth,
            0xB4 => GenericDesktopUsage::SystemDisplayDual,
            0xB5 => GenericDesktopUsage::SystemDisplayToggleIntExt,
            0xB6 => GenericDesktopUsage::SystemDisplaySwapPrimarySecondary,
            0xB7 => GenericDesktopUsage::SystemDisplayLcdAutoscale,
            _ => GenericDesktopUsage::Reserved(v),
        }
    }
}
